### ISSUE TITLE
Prosody extractor output binary output.csv on Linux

### ISSUE THREAD

**Issue by stasbel** [audeering/opensmile#23] opened 2021-09-01 14:47 UTC
1. install opensmile for Linux from source
2. run `./build/progsrc/smilextract/SMILExtract -C config/prosody/prosodyShs.conf -I  my.wav -O prosody.csv`
3. prosody.csv appears to be binary file and is unreadable by text editors

**Comment by stasbel** [comment] 2021-09-01 14:48
with opensmile-python, I can't manage to get it work and specify my hop_length: there is just no options for that

**Comment by stasbel** [comment] 2021-09-01 14:48
PLZ help

**Comment by stasbel** [comment] 2021-09-01 14:51
@frankenjoe

**Comment by stasbel** [comment] 2021-09-01 14:52
I want to somehow extract F0 and loudness with your library and my specific hop length (for alignment along stft len).

**Comment by chausner-audeering** [comment] 2021-09-01 15:05
> prosody.csv appears to be binary file and is unreadable by text editors

The problem is that you specified `-O` which in this case is used to output in HTK format. If you take a look at the end of `prosodyShs.conf`, you see it includes `shared/standard_data_output_lldonly.conf.inc`. In this file, the output command-line parameters are defined. You can see that `-O` is for HTK output:
> filename=\cm[output(O){output.htk}:output HTK binary file for LLD. Use ? as value to disable]

For CSV output, you'll need to use `-csvoutput` instead:

> filename=\cm[csvoutput{?}:output csv file for LLD, disabled by default ?, only written if filename given]

**Comment by chausner-audeering** [comment] 2021-12-29 22:47
I hope your question has been answered, thus I'll close this. If not, feel free to reopen the issue.

**Closed by chausner-audeering** 2021-12-29 22:47 UTC
